######################################################################
# Automatically generated by qmake (3.0) ? 9? 1 19:29:11 2018
######################################################################

QT+=widgets svg xml
TEMPLATE = app
TARGET = exec
INCLUDEPATH += .

# Input
HEADERS += include/dashboard_panel.hpp include/dashboard_panel_define.h
SOURCES += src/dashboard_panel.cpp src/main.cpp
